### ISSUE TITLE
new plugin: code highlighting

### ISSUE THREAD

**Issue by Knorrke** [serlo-org/ory-editor-plugins#9] opened 2017-11-27 10:22 UTC
A simple code highlighting plugin e.g. using https://highlightjs.org/

Maybe it's also possible to have an executable code plugin, e.g. with https://codeocean.com/ or https://tech.io/

**Comment by FWirtz** [comment] 2017-12-05 12:59
What about this: http://slatejs.org/#/code-highlighting?

**Comment by FWirtz** [comment] 2018-01-09 15:38
Almost finished with the syntax highlighter!
## Impressions
![image](https://user-images.githubusercontent.com/6052785/34728374-08a1c94e-f55a-11e7-9223-c37bf4ffafae.png)
![image](https://user-images.githubusercontent.com/6052785/34728492-57874502-f55a-11e7-990a-a57c33d92ce0.png)
![image](https://user-images.githubusercontent.com/6052785/34728518-641927d6-f55a-11e7-9309-820f9c485388.png)

See our [branch plugin/code_highlight](https://github.com/schul-cloud/ory-editor-plugins/tree/plugin/code_highlight) for source.

@Knorrke Is there a way to programatically switch out of the edit mode from inside the component? Once the user clicks "Save", we'd like to automatically leave the edit mode (i.e. `this.props.readOnly = true`). We had a look, but the props don't seem to be supplying such a functionality.

CC @janrenz @Trunken

**Comment by janrenz** [comment] 2018-01-09 15:42
Also in edit mode I would prefer a fixed with font

**Comment by Knorrke** [comment] 2018-01-09 15:46
Cool! :)

I'll look at it in more detail soon. Changing the mode can be done using a trigger:
`editor.trigger.mode.preview()` in your case.

**Comment by janrenz** [comment] 2018-01-09 18:56
And available languages could be a drop down

**Comment by FWirtz** [comment] 2018-01-10 11:16
@janrenz changed the font to `monospace`. Not a big fan of dropdowns with 176 options. Could think of an Autocomplete or alike, but I don't think it's that big of a priority atm.

@Knorrke How can we access the `editor` from within the plugin component? Does it get supplied as a prop?
Also, is there a best practice on persisting a plugins content? I found [this](https://ory.gitbooks.io/editor/content/packages/core.html#saving-and-loading), but that seems to only apply to the editor itself.
I had a look at the Geogebra plugin - it seems that everything there is persisted via input `props`. Could you maybe elaborate on the process? I don't get it yet.

**Comment by Knorrke** [comment] 2018-01-10 12:34
@FWirtz Good point, it's not in the props, so you have to pass it manually. Maybe this helps: https://github.com/ory/editor/issues/443 
Might be a bit tricky to initialize, because you have to create the editor first, but i think it should work with doing something like
```javascript
const editor = new Editor({
  plugins,
  editables: [content],
})

const codePlugin = CodeHighlighting(editor)
editor.addContentPlugin(codePlugin)
```
If it gets too messy, maybe consider if the whole button is even needed, since there already is the editor-button to change to preview mode.

Persisting shouldn't be handled by the plugin itself, apart from having all persistent data in the state. Normally, what an integration of the editor in a cms would do, is to store the serialized version the editor provides in the `onChange` method, as described in the link you found. This serialization also includes the state of all plugins. Have a look at the state i created for the example: https://github.com/serlo-org/ory-editor-plugins/blob/master/example/src/content.js
A Geogebra Plugin is e.g. used in [lines 118-121](https://github.com/serlo-org/ory-editor-plugins/blob/master/example/src/content.js#L118-L121). If you want, you can also add a code-highlighting block to the state there, I havent implemented a persistation mechanism for the example, so you have to do it manually.

**Comment by FWirtz** [comment] 2018-01-10 13:25
@Knorrke I see, thanks for elaborating.
You are right, maybe there is a better way: We want to simply set the state according to the text the user entered in the editor. I just had a look at your Geogebra plugin: You simply **set the state every time the input changes**, right? Should we just do it in the same way? This would spare us the complicated plugin initialisation with an injected editor.

Thanks for the clarification on the persistation. We'll try that.

**Comment by FWirtz** [comment] 2018-01-10 13:53
@Knorrke Just tried the persistation using the state. Works. Thanks!

One thing however: If I use the "Move" tool, all changes seem to get lost. I think that's because our `constructor` gets called again and we set the initial state there. Is that the expected behaviour? If so, what should we do differently?

**Comment by Knorrke** [comment] 2018-01-10 14:25
Ah sorry, i confused the states, since there are two^^ first of all there is the state of a react component e.g. `this.state`, which is changed by `this.setState(....)`. In the geogebra plugin I used this to store the width and height of the iframe. The component gets recreated frequently however, creating the problem you experienced.
The plugin state persisted in the `content.js` is passed as a prop, e.g. `this.props.state` and changed using the `this.props.onChange(...)` method. I think thats what you'd need to use, and then it shouldn't reset anymore. Sorry for the confusion! You shouldnt implement a initialization than, since its a prop, but you can use something like:

```javascript
const { state } = this.props;
//option 1
const foo = state.foo || 'default value';

//option 2
return state.bar 
  ? (<div>{state.bar}</div>) 
  : (<div>default text</div>)
```

**Comment by FWirtz** [comment] 2018-01-10 15:35
Wow, that's a little confusing, but I think I get it, thanks @Knorrke!
Is that `state` via `props` shared between all components or at least somewhat isolated?

Meaning: If I set the state of `example` using `this.props.onChange(...)` in my `highlight` component, would that crash with me setting the state `example` using the same method from within `geogebra`?
Should I therefore prefix all states I set via `props.onChange(...)` or don't I need to worry about that?

**Comment by FWirtz** [comment] 2018-01-10 15:47
Just to keep you posted on our roadmap:
I am back in office on Tuesday. 
I'll finish the state thingy you described and therefore **finish the highlight plugin**.
Also, I feel like the creating-a-plugin `README`**/docs could use an extension** (see countless comments above 😉), so **I'll supply a PR** on Tuesday as well.
Another ToDo for next week for us is **including the `ory-editor` into the Schul-Cloud dev** branch.

So long @Knorrke : Have a lovely weekend, thanks for your **enormous** patience and see you next week! 😊 👋 

CC @janrenz

**Comment by Knorrke** [comment] 2018-01-10 19:59
Its completely isolated, no worries about naming. Its just that the persistent state is actually handled outside of the plugin.

Its even kind of in the docs, since its used in the "Writing a plugin" section, but its not really explained, so i get the confusion! The PR would be much appretiated, thanks in advance! :)

Nice weekend to you too. Looking foreward for the plugin, looks really cool already :-)

**Comment by FWirtz** [comment] 2018-01-17 09:37
Ok, just finished the plugin! See #15 for reference.

Wow, the [Writing a plugin](https://ory.gitbooks.io/editor/content/tutorials.html#writing-plugins) section is actually really helpful! I think we should reference it in the README, as I totally forgot about it, haha

**Comment by FWirtz** [comment] 2018-01-17 10:23
Also, added 2 more sections to the FAQ in #16.
Please let me know how you feel about these, @Knorrke. 😊

**Closed** 2018-01-23 11:07 UTC
